services:
  alice:
    build:
      context: ./alice
    container_name: alice_api
    restart: unless-stopped
    init: true

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - alice

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - esnet

  data-loader:
    build:
      context: etl
      dockerfile: Dockerfile
    container_name: loader-movies
    depends_on:
      - elasticsearch
    networks:
      - esnet
  
  nlp-module:
    build:
      context: nlp
      dockerfile: Dockerfile
    container_name: nlp-module
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
    depends_on:
      - elasticsearch
    networks:
      - esnet

networks:
  esnet:
    driver: bridge

volumes:
  elasticdata: